/*
 * xHarbour build 1.2.1 Intl. (SimpLex) (Rev. 6406)
 * Generated C source code from <.\\source\\prg\\TDOLPSRV.PRG>
 * Command: .\source\prg\TDOLPSRV.PRG /N /W /w /es2 /O.\objx\ /I.\include;\XHARBOUR\include; 
 * Created: 2010.06.12 09:59:33 (Borland C++ 5.5.1 (32 bit))
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ ".\\source\\prg\\TDOLPSRV.PRG"

HB_FUNC( TDOLPHINSRV );
HB_FUNC_STATIC( TDOLPHINSRV_NEW );
HB_FUNC_INITSTATICS();

/* Skipped DEFERRED call to: 'DIVERTCONSTRUCTORCALL' */
HB_FUNC_EXTERN( HBCLASS );
HB_FUNC_EXTERN( HBOBJECT );
HB_FUNC_EXTERN( __CLSACTIVE );
HB_FUNC_EXTERN( __CLSINST );
HB_FUNC_EXTERN( __OBJHASMSG );
HB_FUNC_EXTERN( HB_APARAMS );
HB_FUNC_EXTERN( PCOUNT );
HB_FUNC_EXTERN( SQLCONNECT );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 10

#include "hbapi.h"

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_TDOLPSRV )
{ "DIVERTCONSTRUCTORCALL", {HB_FS_PUBLIC | HB_FS_DEFERRED}, {NULL}, NULL },
{ "TDOLPHINSRV", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( TDOLPHINSRV )}, &ModuleFakeDyn },
{ "NEW", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "HBCLASS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBCLASS )}, NULL },
{ "CLASSH", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "HBOBJECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBOBJECT )}, NULL },
{ "ADDMULTIDATA", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ADDMETHOD", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TDOLPHINSRV_NEW", {HB_FS_STATIC | HB_FS_LOCAL}, {HB_FUNCNAME( TDOLPHINSRV_NEW )}, &ModuleFakeDyn },
{ "__CLSACTIVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __CLSACTIVE )}, NULL },
{ "HCLASS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "REFRESH", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CREATE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "__CLSINST", {HB_FS_PUBLIC}, {HB_FUNCNAME( __CLSINST )}, NULL },
{ "__OBJHASMSG", {HB_FS_PUBLIC}, {HB_FUNCNAME( __OBJHASMSG )}, NULL },
{ "INITCLASS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "HB_APARAMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_APARAMS )}, NULL },
{ "PCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PCOUNT )}, NULL },
{ "_CSERVER", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_CUSER", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_CPASSWORD", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_NPORT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_NFLAGS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_HMYSQL", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SQLCONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SQLCONNECT )}, NULL },
{ "_LERROR", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_BONERROR", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_NINTERNALERROR", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "HMYSQL", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "(_INITSTATICS00001)", {HB_FS_INITEXIT}, {hb_INITSTATICS}, &ModuleFakeDyn }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_TDOLPSRV )

#if defined(__ICL)
   #pragma warning(disable:177)
#endif

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_TDOLPSRV
#elif defined(HB_MSC_STARTUP)
   #if defined( HB_OS_WIN_64 )
      #pragma section( HB_MSC_START_SEGMENT, long, read )
   #endif
   #pragma data_seg( HB_MSC_START_SEGMENT )
   static HB_$INITSYM hb_vm_auto_SymbolInit_TDOLPSRV = hb_vm_SymbolInit_TDOLPSRV;
   #pragma data_seg()
#endif

HB_FUNC( TDOLPHINSRV )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 255,	/* locals, params */
	HB_P_SFRAME, 29, 0,	/* symbol (_INITSTATICS) */
	HB_P_LOCALNEARSETINT, 2, 1, 0,	/* NSCOPE 1*/
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSE, 144, 1,	/* 400 (abs: 00415) */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 3,	/* HBCLASS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'T', 'D', 'o', 'l', 'p', 'h', 'i', 'n', 'S', 'r', 'v', 0, 
	HB_P_MESSAGE, 4, 0,	/* CLASSH */
	HB_P_PUSHSYMNEAR, 5,	/* HBOBJECT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_SENDSHORT, 2,
	HB_P_POPSTATIC, 1, 0,	/* S_OCLASS */
/* 00058 */ HB_P_BASELINE, 19, 0,	/* 19 */
	HB_P_MESSAGE, 6, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'b', 'O', 'n', 'E', 'r', 'r', 'o', 'r', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00090 */ HB_P_LINEOFFSET, 2,	/* 21 */
	HB_P_MESSAGE, 6, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'c', 'P', 'a', 's', 's', 'w', 'o', 'r', 'd', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00122 */ HB_P_LINEOFFSET, 3,	/* 22 */
	HB_P_MESSAGE, 6, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'c', 'S', 'e', 'r', 'v', 'e', 'r', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00152 */ HB_P_LINEOFFSET, 4,	/* 23 */
	HB_P_MESSAGE, 6, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'c', 'U', 's', 'e', 'r', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00180 */ HB_P_LINEOFFSET, 6,	/* 25 */
	HB_P_MESSAGE, 6, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'h', 'M', 'y', 's', 'q', 'l', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00209 */ HB_P_LINEOFFSET, 8,	/* 27 */
	HB_P_MESSAGE, 6, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'l', 'E', 'r', 'r', 'o', 'r', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00238 */ HB_P_LINEOFFSET, 10,	/* 29 */
	HB_P_MESSAGE, 6, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'n', 'F', 'l', 'a', 'g', 's', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00267 */ HB_P_LINEOFFSET, 11,	/* 30 */
	HB_P_MESSAGE, 6, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'n', 'I', 'n', 't', 'e', 'r', 'n', 'a', 'l', 'E', 'r', 'r', 'o', 'r', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00304 */ HB_P_LINEOFFSET, 12,	/* 31 */
	HB_P_MESSAGE, 6, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'n', 'P', 'o', 'r', 't', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00332 */ HB_P_LINEOFFSET, 14,	/* 33 */
	HB_P_MESSAGE, 7, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'N', 'e', 'w', 0, 
	HB_P_PUSHSYMNEAR, 8,	/* TDOLPHINSRV_NEW */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
	HB_P_MESSAGE, 12, 0,	/* CREATE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 13,	/* __CLSINST */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 10, 0,	/* HCLASS */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 14,	/* __OBJHASMSG */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'I', 'n', 'i', 't', 'C', 'l', 'a', 's', 's', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPFALSENEAR, 32,	/* 32 (abs: 00430) */
	HB_P_MESSAGE, 15, 0,	/* INITCLASS */
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 16,	/* HB_APARAMS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 17,	/* 17 (abs: 00430) */
	HB_P_PUSHSYMNEAR, 13,	/* __CLSINST */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 10, 0,	/* HCLASS */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 17,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00447) */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSYMNEAR, 0,	/* DIVERTCONSTRUCTORCALL */
	HB_P_FUNCPTR,
	HB_P_ZERO,
	HB_P_DIVERTOF,
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00451 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC_STATIC( TDOLPHINSRV_NEW )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 6,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 7,	/* SELF */
/* 00006 */ HB_P_BASELINE, 40, 0,	/* 40 */
	HB_P_MESSAGE, 18, 0,	/* _CSERVER */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_PUSHLOCALNEAR, 1,	/* CSERVER */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00019 */ HB_P_LINEOFFSET, 1,	/* 41 */
	HB_P_MESSAGE, 19, 0,	/* _CUSER */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_PUSHLOCALNEAR, 2,	/* CUSER */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00031 */ HB_P_LINEOFFSET, 2,	/* 42 */
	HB_P_MESSAGE, 20, 0,	/* _CPASSWORD */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_PUSHLOCALNEAR, 3,	/* CPASSWORD */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00043 */ HB_P_LINEOFFSET, 3,	/* 43 */
	HB_P_MESSAGE, 21, 0,	/* _NPORT */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_PUSHLOCALNEAR, 4,	/* NPORT */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00055 */ HB_P_LINEOFFSET, 4,	/* 44 */
	HB_P_MESSAGE, 22, 0,	/* _NFLAGS */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_PUSHLOCALNEAR, 5,	/* NFLAGS */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00067 */ HB_P_LINEOFFSET, 5,	/* 45 */
	HB_P_MESSAGE, 23, 0,	/* _HMYSQL */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_PUSHSYMNEAR, 24,	/* SQLCONNECT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* CSERVER */
	HB_P_PUSHLOCALNEAR, 2,	/* CUSER */
	HB_P_PUSHLOCALNEAR, 3,	/* CPASSWORD */
	HB_P_PUSHLOCALNEAR, 4,	/* NPORT */
	HB_P_PUSHLOCALNEAR, 5,	/* NFLAGS */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00092 */ HB_P_LINEOFFSET, 6,	/* 46 */
	HB_P_MESSAGE, 25, 0,	/* _LERROR */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00103 */ HB_P_LINEOFFSET, 7,	/* 47 */
	HB_P_MESSAGE, 26, 0,	/* _BONERROR */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_PUSHLOCALNEAR, 6,	/* BONERROR */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00115 */ HB_P_LINEOFFSET, 8,	/* 48 */
	HB_P_MESSAGE, 27, 0,	/* _NINTERNALERROR */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00126 */ HB_P_LINEOFFSET, 10,	/* 50 */
	HB_P_MESSAGE, 28, 0,	/* HMYSQL */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_ZERO,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 13,	/* 13 (abs: 00150) */
/* 00139 */ HB_P_LINEOFFSET, 11,	/* 51 */
	HB_P_MESSAGE, 25, 0,	/* _LERROR */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00150 */ HB_P_LINEOFFSET, 15,	/* 55 */
	HB_P_PUSHLOCALNEAR, 7,	/* SELF */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00156 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC_INITSTATICS()
{
   static const BYTE pcode[] =
   {
	HB_P_STATICS, 29, 0, 1, 0,	/* symbol (_INITSTATICS), 1 statics */
	HB_P_ENDPROC
/* 00006 */
   };

   hb_vmExecute( pcode, symbols );
}

